#!/bin/sh
LOCK=/home/$USER/.config/eww/temp/cc.lock
eww=/home/$USER/.local/bin/eww

if [ -f "$LOCK" ]; then
    rm -rf "$LOCK"
    $eww close notification
else
    touch "$LOCK"
    $eww open notification
fi
